apiVersion: aws.amazon.com/v1beta1
kind: PartnerOffering
metadata:
  description: A comprehensive tool for designing and developing interactive automotive user interfaces, offering advanced graphics rendering, a powerful scripting engine, and seamless integration of 2D and 3D UI components.
  name: kanzi-studio-dev-env
  tags:
  - aws-partner-sdv
  title: Rightware Kanzi Studio Dev Env
spec:
  type: SaaS
  author: dSpace
  authorPageUrl: https://aws.amazon.com/automotive/partners
  url: https://18.246.61.139:8443/
