apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: drivesphere-partner-offerings
  description: A collection of all CMS partner offerings
spec:
  targets:
    - ./partner-offerings/elektrobit/virtual-ivi-for-android.yaml
    - ./partner-offerings/gitlab/project-repo.yaml
    - ./partner-offerings/genymobile/genymotion-cloud-car.yaml
    - ./partner-offerings/here-technologies/here-tour-planning.yaml
    - ./partner-offerings/panasonic/vskipgen-infotainment-ecu.yaml
    - ./partner-offerings/rightware/kanzi-studio-dev-env.yaml
